#!/usr/bin/env python
import optparse
import logging

import reSTsite


def main(args):
    parser = optparse.OptionParser(usage='%prog [options]', version='%prog 0.1')
    parser.add_option('-s', '--sitepath',
                      dest='site_path',
                      help='Root directory of site [default: current dir]')
    parser.add_option('-c', '--config',
                      dest='config',
                      help='Configuration file')
    parser.add_option('-q', '--quiet',
                      action='store_const',
                      dest='loglevel',
                      const=logging.ERROR)
    parser.add_option('-d', '--debug',
                      action='store_const',
                      dest='loglevel',
                      const=logging.DEBUG)
    parser.set_defaults(site_path='',
                        config=None,
                        loglevel=logging.INFO)

    options, args = parser.parse_args(args)

    if len(args) > 0:
        parser.error('Unrecognised options: ' + str(args))

    logging.basicConfig(format='[%(levelname)-8s] %(name)s: %(message)s',
                        level=options.loglevel)

    site = reSTsite.Site(options.site_path, options.config)
    site.process()
    site.generate()


if __name__ == '__main__':
    import sys
    main(sys.argv[1:])
