#!/usr/bin/env python

import logging
logging.basicConfig(level=logging.DEBUG,
        format='%(levelname)-8s [%(name)s] %(message)s')
log = logging.getLogger('reSTsite')

from optparse import OptionParser
parser = OptionParser()
parser.add_option('-r', '--root', dest='root', help='root directory',
        metavar='DIR', default='.')
(options, args) = parser.parse_args()

import reSTsite
site = reSTsite.Site(options.root)
site.process()

exit()

import os.path
import sys

import reSTsite
import reSTsite.handlers
import reSTsite.filesystem as fs
from reSTsite import settings

configfile = sys.argv[1] if len(sys.argv) > 1 else 'config.yaml'
if os.path.exists(configfile):
    reSTsite.load_settings(configfile)
else:
    log.error('Configuration file missing')

import reSTsite.handlers
import reSTsite.filesystem as fs

reSTsite.handlers.load_handlers(settings['handlers'])
handlers = reSTsite.handlers.get_extension_handlers()

from reSTsite.templates import TemplateEngine
tpl = TemplateEngine(settings['template_path'])

# Walk files to be copied
for full, rel, ext in fs.walk(settings['static_path']):
    log.info('Copying static %s' % rel)
    fs.copy(full, os.path.join(settings['deploy_path'], rel))

# Walk files to be processed
for full, rel, ext in fs.walk(settings['site_path']):
    # Skip unhandled extensions
    if ext in handlers:
        log.info('Processing %s' % rel)
        handler = handlers[ext](full, rel)
        dest = os.path.join(settings['deploy_path'], handler.get_target_path())
        context = handler.to_context()
        data = tpl.render(context['template'], context)
        fs.create(dest).write(data)
